# Generated by Django 3.2.9 on 2022-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='documnets_aproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='documnets_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadharCard',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='feeReciept',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photoId',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
