# Generated by Django 3.2.9 on 2022-07-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0002_auto_20220718_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_cgpa',
            field=models.FloatField(default=0),
        ),
    ]
