# Generated by Django 3.2.9 on 2022-07-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0003_student_current_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='alloted',
            field=models.BooleanField(default=False),
        ),
    ]
