# Generated by Django 4.0.4 on 2022-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0004_hostel_alloted'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='preferences',
            field=models.IntegerField(default=0),
        ),
    ]
