# Generated by Django 4.0.4 on 2022-07-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0005_room_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prefRec',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='preferences',
            field=models.TextField(null=True),
        ),
    ]
